apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
  namespace: dp-app
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: dp-app.apctech.ru
  dnsNames:
  - dp-app.apctech.ru