---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dp-app
  namespace: dp-app
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-staging"
  #   acme.cert-manager.io/http01-edit-in-place: "true"
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   kubernetes.io/ingress.allow-http: "true"
  #   kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: dp-app.apctech.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dp-app
            port: 
              number: 80
  # tls:
  #   - hosts:
  #     - dp-app.apctech.ru
  #     secretName: dp-app-tls